<?php

namespace PIDEVBundle\Repository;

/**
 * LigneAchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneAchatRepository extends \Doctrine\ORM\EntityRepository
{
}
